services:
    anime_db.my_anime_list_sync.listener.item:
        class: AnimeDb\Bundle\MyAnimeListSyncBundle\Event\Listener\Item
        arguments:
            - %anime_db.my_anime_list_sync.user.name%
            - %anime_db.my_anime_list_sync.user.password%
            - %anime_db.my_anime_list_sync.sync.remove%
            - %anime_db.my_anime_list_sync.sync.insert%
            - %anime_db.my_anime_list_sync.sync.update%
        tags: [{ name: doctrine.event_listener, event: postRemove, method: onPostRemove }]
        tags: [{ name: doctrine.event_listener, event: postPersist, method: onPostPersist }]
        tags: [{ name: doctrine.event_listener, event: postUpdate, method: onPostUpdate }]