services:
    anime_db.my_anime_list_sync.listener.item:
        class: AnimeDb\Bundle\MyAnimeListSyncBundle\Event\Listener\Item
        tags: [{ name: doctrine.event_listener, event: postRemove, method: onPostRemove }]
        tags: [{ name: doctrine.event_listener, event: postPersist, method: onPostPersist }]
        tags: [{ name: doctrine.event_listener, event: postUpdate, method: onPostUpdate }]